version '3.1'

services:
	zookeeper:
	image: docker pull wurstmeister/zookeeper
	container_name: zookeeper
	port:
	  -"2181:2181"
	  
	  
    zookeeper:
	image: docker pull wurstmeister/kafka
	container_name: kafka
	port:
	  -"9092:9092"
	  
	environment:
		KAFKA_ADVERTISED_HOST_NAME: locathost
		KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
	
	
